
#This Project is about COVID-19 desease

# A pneumonia of unknown cause detected in Wuhan, China was first internationally reported from China on 31 December 2019. Today we know this virus as Coronavirus. COVID-19 which stands for COronaVIrus Disease is the disease caused by this virus. Since then, the world has been engaged in the fight against this pandemic. Several measures have therefore been taken to "flatten the curve". We have consequently experienced social distancing and many people have passed away as well.

#In the solidarity to face this unprecedented global crisis, several organizations did not hesitate to share several datasets allowing the conduction of several kinds of analysis in order to understand this pandemic.

#This dataset was collected between the 20th of January and the 1st of June 2020. The purpose of this Guided Project is to build our skills and understanding of the data analysis workflow by evaluating the COVID-19 situation through this dataset.

#My analysis tries to provide an answer to this question: Which countries have had the highest number of positive cases against the number of tests?


#At first we need to download our data and explore it briefly


data <- read_csv('covid19.csv')

# Explore the dimensions of our dataset

dim(data)

# 10903    14

# Let's explore the column names:

vector_cols <- colnames(data)

vector_cols

# [1] "Date"                    "Continent_Name"          "Two_Letter_Country_Code"
# [4] "Country_Region"          "Province_State"          "positive"               
# [7] "hospitalized"            "recovered"               "death"                  
# [10] "total_tested"            "active"                  "hospitalizedCurr"       
# [13] "daily_tested"            "daily_positive"    

#Let's explore the first few rows of our data

head(data)

# Let's explore the summary of the covid_df dataset using the function glimpse() from the tibble package.

library(tibble)

glimpse(data)

# Looking at the few lines of our dataset we displayed in the previous step, we can see that the Province_State column mixes data from different levels: country level and state/province level. Since we cannot run an analysis on all these levels at the same time, we need to filter what we are interested in.


data_all_states <- filter(data, Province_State == 'All States')
data_all_states <- data_all_states[-5]                

# Revisiting the description of the dataset columns, we can notice that there are columns that provide daily information and others that provide cumulative information.
#Hence, we should manage those cases (columns with cumulative and daily information) separately because we cannot work with both together. Actually, our analysis would be biased if we made the mistake of comparing a column containing cumulative data and another one containing only one-day data. This is another example of a situation that we want to know from the beginning of the project in order to better analyze our dataset.

#Thereafter, we work mainly with daily data. So let's extract the columns related to the daily measures.

data_all_states_daily <- data_all_states[c('Date', 'Country_Region', 'active', 'hospitalizedCurr', 'daily_tested', 'daily_positive')]

# Our goal here is to extract the top ten cases countries data. Acting like a data scientist, at this step, these are the questions we are asking ourselves. How can we get the overall number of COVID-19 tested, positive, active and hospitalized cases by country since we currently have daily data?

data_all_states_daily_sum<- data_all_states_daily %>%
       group_by (Country_Region) %>%
       summarize (
           tested = sum(daily_tested),
           positive = sum(daily_positive),
           active = sum(active),
           hospitaluzes = sum(hospitalizedCurr)) %>%
      arrange(-tested)
           
covid_top_10 <- head(data_all_states_daily_sum, 10)       


#Our goal is to answer this question: Which countries have had the highest number of positive cases against the number of tests?

countries <- covid_top_10$Country_Region
tested_cases <- covid_top_10$tested
positive_cases <- covid_top_10$positive
active_cases <- covid_top_10$active
hospitalized_cases <- covid_top_10$hospitaluzes


names(tested_cases) <- countries
names(positive_cases) <- countries
names(active_cases) <- countries
names(hospitalized_cases) <- countries


tested_cases

# tested_cases
#United States         Russia          Italy          India         Turkey         Canada 
#     17282363       10542266        4091291        3692851        2031192        1654779 
#United Kingdom      Australia           Peru         Poland 
#      1473672        1252900         976790         928256 


positive_tested_top <- positive_cases / tested_cases
positive_tested_top

#United States         Russia          Italy          India         Turkey         Canada 
#   0.108618191    0.038546552    0.061523368    0.016507300    0.080711720    0.054915490 
#United Kingdom      Australia           Peru         Poland 
#0.113260617    0.005746668    0.060910738    0.025840932 

As we can see from the positive_tested_top the highest ratio United_Kingdom, United_States and Turkey have most positive cases.

positive_tested_top_3 <- c('United Kingdom'=0.113260617, 'United States'=0.108618191, 'Turkey' =0.080711720)

#To make sure we won't lose other information about these countries we can create a matrix that contains the ratio and the overall number of COVID-19 tested, positive, active and hospitalized cases.

united_kingdom <- c(0.11, 1473672, 166909, 0, 0)
united_states <- c(0.10, 17282363, 1877179, 0, 0)
turkey <- c(0.08, 2031192, 163941, 2980960, 0)


covid_mat <- rbind(united_kingdom, united_states, turkey)
colnames(covid_mat) <- c("ratio", "tested", "positive", "active", "hospitalized")

covid_mat

#               ratio   tested positive  active hospitalized
#united_kingdom  0.11  1473672   166909       0            0
#united_states   0.10 17282363  1877179       0            0
#turkey          0.08  2031192   163941 2980960            0


question <- "Which countries have had the highest number of positive cases against the number of tests?"

answer <- c("Positive tested cases" = positive_tested_top_3)


dataframes <- c(data, data_all_states, data_all_states_daily, data_all_states_daily_sum)
matrices <- c(covid_mat)
vectors <- c(active_cases, countries, hospitalized_cases, positive_cases, positive_tested_top, tested_cases, positive_tested_top_3, turkey, united_kingdom, united_states)
data_structure_list <- c('dataframes' = dataframes, 'matrices' = matrices, 'vectors' = vectors)


covid_analysis_list <- c(question, answer, data_structure_list)

covid_analysis_list[2]

#`Positive tested cases.United Kingdom`
#United Kingdom  United States         Turkey 
# 0.11326062     0.10861819     0.08071172 


          
                